image_width: 1280
image_height: 960
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1795.79795,    0.     ,  722.92913,
            0.     , 1793.5645 ,  557.38323,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.079760, 0.105841, -0.000335, -0.001349, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1779.27551,    0.     ,  722.54359,    0.     ,
            0.     , 1781.92859,  557.37646,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]